name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 2 * * 0'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
    - uses: ruby/setup-ruby@7d546f4868fb108ed378764d873683f920672ae2 # v1.149.0
      with:
        ruby-version: "2.7.2"
    - run: gem install bundler:1.17.3
    - run: bundle install
    - run: bundle exec jekyll build
