name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 2 * * 0'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - uses: ruby/setup-ruby@d4526a55538b775af234ba4af27118ed6f8f6677 # v1.172.0
      with:
        ruby-version: "2.7.2"
    - run: gem install bundler:1.17.3
    - run: bundle install
    - run: bundle exec jekyll build
